version: '3'
services:
  spire-server:
    image: gcr.io/spiffe-io/spire-server:0.9.0
    volumes:
      - ./server:/run/spire/conf
    command: ["-config", "/run/spire/conf/server.conf"]
  spire-agent:
    image: gcr.io/spiffe-io/spire-agent:0.9.0
    volumes:
      - /tmp/spire-agent:/run/spire
    command: ["-config", "/run/spire/agent.conf"]
    environment:
      - container=spire-agent
